[package]
name = "raop"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1.37"
bytes = "1.4.0"
lazy_static = "1.4.0"
openssl = "0.10.50"
# Until version isn't bumped so I can pull it from crates.io
tower = { version = "0.4.13", features = ["util"] }
rtsp-types = { git = "https://github.com/sdroege/rtsp-types", branch = "main" }
sdp-types = "0.1.5"
rtp-rs = "0.6.0"
futures = "0.3.28"
# TODO remove it with smaller deps
tokio = { version = "1.27.0", features = ["full", "io-util"] }
tracing-subscriber = "0.3.17"
symphonia-core = "0.5.2"
crossbeam-utils = "0.8.15"
url = "2.3.1"
dashmap = "5.4.0"
strp = "1.1.2"
tokio-util = { version = "0.7.8", features = ["codec"] }
