[package]
name = "raop"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1.37"
bytes = "1.4.0"
url = "2.3.1"
lazy_static = "1.4.0"
openssl = "0.10.50"
tower = { version = "0.4.13", features = ["util"] }
rtsp-types = "0.1.0"
sdp-types = "0.1.5"
rtp-rs = "0.6.0"
futures = "0.3.28"
