[package]
name = "raop"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.4.0"
lazy_static = "1.4.0"
# Until version isn't bumped so I can pull it from crates.io
rtsp-types = { git = "https://github.com/sdroege/rtsp-types", branch = "main" }
sdp-types = "0.1.5"
tower = { version = "0.4.13", features = ["util"] }
futures = "0.3.28"
tokio = { version = "1.27.0", features = ["full", "io-util"] }
tokio-util = { version = "0.7.7", features = ["codec"] }
tracing = "0.1.37"
openssl = "0.10.50"
